extends Node

const SERVER_TERRAIN_COLLISION_LAYER = 0

const SERVER_TERRAIN_COUNTABLE_COLLISION_LAYER = 12

const SERVER_NPC_COLLISION_LAYER = 13

const SERVER_PLAYER_COLLISION_LAYER = 10

const SERVER_BOSS_COLLISION_LAYER = 15

const CLIENT_NPC_COLLISION_LAYER = 14

const CLIENT_PLAYER_COLLISION_LAYER = 11

const CLIENT_CURRENT_PLAYER_COLLISION_LAYER = 20




