extends Node

var SERVER_TERRAIN_COLLISION_LAYER = 0

var SERVER_TERRAIN_COUNTABLE_COLLISION_LAYER = 12

var SERVER_NPC_COLLISION_LAYER = 13

var SERVER_PLAYER_COLLISION_LAYER = 10

var CLIENT_NPC_COLLISION_LAYER

var CLIENT_PLAYER_COLLISION_LAYER = 11

var CLIENT_CURRENT_PLAYER_COLLISION_LAYER




