

pub const SERVER_TERRAIN_COLLISION_LAYER:u8 = 0;

pub const SERVER_TERRAIN_COUNTABLE_COLLISION_LAYER:u8 = 12;

pub const SERVER_NPC_COLLISION_LAYER:u8 = 13;

pub const SERVER_PLAYER_COLLISION_LAYER:u8 = 10;

pub const SERVER_BOSS_COLLISION_LAYER:u8 = 15;

pub const CLIENT_NPC_COLLISION_LAYER:u8 = 14;

pub const CLIENT_PLAYER_COLLISION_LAYER:u8 = 11;

pub const CLIENT_CURRENT_PLAYER_COLLISION_LAYER:u8 = 20;

pub const CLIENT_SHOPS_COLLISION_LAYER:u8 = 21;



